# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  create:
    branches: 
      - release/**

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'MavSdk.Net.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Get Build Version
      run: |
        Import-Module ./build/GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --configuration Release --no-restore
    - name: Test
      run: dotnet test $SOLUTION --no-build --verbosity normal
    - name: Prep packages
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget add source --username tank104 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tank104/index.json"
    - name: Publish to GitHub packages 
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
    - name: Publish to nuget.org
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json"